
export const ARTICLES_LOADING = "ARTICLES_LOADING";
export const RECEIVED_ARTICLES = "RECEIVED_ARTICLES";
export const FETCH_ARTICLE_ERROR = "FETCH_ARTICLE_ERROR";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const SET_COUNTRIES = "SET_COUNTRIES";
export const CLEAR_STORE = "CLEAR_STORE";
export const REQUEST_PARAMS_MISSING = "REQUEST_PARAMS_MISSING";
export const NO_ARTICLES = "NO_ARTICLES";
